### ISSUE TITLE
Support for ES5

### ISSUE THREAD

**Issue by wongjiahau** [ethanent/phin#13]
I hope to has this feature because Create-React-App cannot minify ES6 code, you can read more about it [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).

**Comment by ethanent** [comment]
Thanks for the suggestion, but I don't fully see the importance of supporting older JS implementations in most cases. :)

I'm sorry, but it's really Facebook's job to keep up with the latest (or at least Node LTS implemented) JS spec.

**Comment by wongjiahau** [comment]
@ethanent Anyway this is a very good library, because `request.js` is a monolithic package.

**Comment by ethanent** [comment]
@wongjiahau Thanks! I'm really glad you're enjoying it. 😁
