### ISSUE TITLE
Add JSON Post/Put support

### ISSUE THREAD

**Issue by aequasi** [ethanent/phin#16]
Add support for posting/putting JSON.

Would be cool if we could just do this:

```javascript
p({url: "some url", method: "POST", json: {foo: 'bar'});
```

Which would set the `Content-Type` and `Accepts` headers to `application/json`

**Comment by ethanent** [comment]
Thanks for the suggestion. This feature already kind of exists. The `data` phinOptions option is automatically JSON stringified if it's an object. (The `Content-Type` header isn't automatically set, but that's really easy for developers to do if they'd like.)

**Comment by matteocontrini** [comment]
@ethanent I think the `Content-Type` should be added automatically, I've just spent the last 20 minutes understanding why the server ignored my POST data...

**Comment by thelinuxlich** [comment]
Why close this issue? Any API sending JSON without these headers is totally wrong.

**Comment by ethanent** [comment]
@matteocontrini @thelinuxlich Thanks for the suggestion. 

As of `phin@2.0.0`, the `Content-Type` header is defined automatically for `JSON.stringify`-ed request bodies. :)
