### ISSUE TITLE
Not suitable for browser use

### ISSUE THREAD

**Issue by czycha** [ethanent/phin#19]
Despite being ultra-lightweight for server side use, this does not extend to the browser. Using Webpack, phin compiles to ~148KB (compare that to ~14.6KB for axios). At the least, I think that there should be a disclaimer about this . At the most, it would be great if a browser-ready version of phin was made.

**Comment by ethanent** [comment]
Ok, interesting. I've never attempted to use phin in frontend development as the `fetch` library seems to handle most of my HTTP needs. Feel free to make your own improvements to your fork as you feel are necessary for frontend use! (Frontend would be cool to use for consistency between client and server HTTP libraries!)
