### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by julianxhokaxhiu** [ethanent/phin#20]
Hi,

I'm using this library at the moment which is very cool as it is small, lightweight and it does its job pretty well. Although I currently miss one small feature that is the ability to follow redirects if a specific URL replies back with any Location header inside of it.

Would you mind implementing it in your own library?

Thank you in advance,
Julian

**Comment by ethanent** [comment]
Thanks for the feature request. This would definitely be possible to do with a wrapper client, but I do see why it could be useful to have built-in! I'll leave the issue open as a potential feature addition!

**Comment by ethanent** [comment]
Thanks for the suggestion! This feature has been implemented in minor release 3.1.0. (71b308f284f0196d2d088c0de4f50621920f72bb)

Adding an option to specify a maximum number of redirects to follow is on the agenda.
