### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by KenWa51** [ethanent/phin#23]
Error: Cannot find module 'phin' However I've installed it??
It just doesn't make sense....

+ phin@2.9.3
updated 1 package and audited 1021 packages in 1.734s
found 0 vulnerabilities

**Comment by ethanent** [comment]
Thanks for the report. This may be an installation issue so I'll close the issue for now. Are you sure that the place you're requiring phin from is in the same folder or a child folder below the `node_modules` folder for your package?
