### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [ethanent/phin#28]
Hi,

another missing feature I noticed missing, compared to `require`, is the support for HTTP proxy. The best would be to auto detect it based on environment variables and/or also as an option when calling phin.

What do you think? Are you interested in implementing it?

Best regards,
Julian

**Comment by julianxhokaxhiu** [comment]
I was looking at some docus around and would be also awesome if you could provide an option to pass an Agent to the HTTP request. Then I would be able to autonomously pass an Agent done with https://www.npmjs.com/package/proxy-agent

**Comment by ethanent** [comment]
✔️ phin 3.3.0 adds this functionality!

```js
await p({
   'url': 'https://ethanent.me',
   'core': {
      'agent': myAgent // Assuming you'd previously created Agent myAgent
   }
})
```
