### ISSUE TITLE
How can we send file with phin?

### ISSUE THREAD

**Issue by Dobby85** [ethanent/phin#35]
Hi,

I'm trying sending a file with phin but without results. I tried in data of in form, nothing works.
Is there a way to send a file with phin? If yes, how can we do it?

Thanks,

Maxime

**Comment by Dobby85** [comment]
Did somenone has a solution? @ethanent 

Thanks,

Maxime

**Comment by ethanent** [comment]
Hi! To send a file, simply set the body of your request to the file data like so...

```js
const fileBuffer = fs.readFileSync(path.join(__dirname, 'myfile.png'))

await p({
   'url': 'https://ethanent.me/nonexistentEndpoint',
   'method': 'POST',
   'data': fileBuffer
})
```
