### ISSUE TITLE
How to use http-auth?

### ISSUE THREAD

**Issue by ashraful-islam** [ethanent/phin#41]
Hello!

I looked through documentation & source code, but neither mentions how to provide authorization parameters.

For example, in axios, there is a configuration parameter `auth` used to pass the username, password to perform a request to protected service.

How do I pass these parameters in phin?

Thanks!

**Comment by jumoog** [comment]
its just a normal HTTP Header
```
var header = user + ':' + pass;
header = Buffer.from(header, 'utf8').toString('base64');
var authHeader = 'Basic ' + header;
```

```
await p({
	'url': 'https://ethanent.me/name',
	'core': {
		'authorization': authHeader
	}
})

```

**Comment by ethanent** [comment]
Thank you, @jumoog.
