### ISSUE TITLE
Documentation link not working as expected.

### ISSUE THREAD

**Issue by cvweiss** [ethanent/phin#43]
On this page: https://ethanent.github.io/phin/

The first link for "Full documentation" is a link to the same page. Having a link with the text "Full documentation" implies that the link has more documentation than is offered on the current page, and can be confusing to the person attempting to read more documentation on phin. Same applies for the section "Full Documentation".

**Comment by ethanent** [comment]
I see what you mean. The link should probably just go to the ["global"](https://ethanent.github.io/phin/global.html) page.

**Comment by rosman21** [comment]
it still isn't working

**Comment by ethanent** [comment]
@rosman21 I recommend using the link I sent previously. TODO: Update link in README

**Comment by ethanent** [comment]
Updated in README on Github. This should be published to NPM in a future release.
