### ISSUE TITLE
How to use multipart/form-data

### ISSUE THREAD

**Issue by ASaiAnudeep** [ethanent/phin#47]
Hi,

I am trying to make a request with **multipart/form-data**. Is it possible to send such requests in **phin**.

Can I use [form-data](https://www.npmjs.com/package/form-data) in **phin**??

**Comment by ThatTonybo** [comment]
As far as I'm aware either parse a JSON object in the request's `{ data }` field, or you could try using form-data.

**Comment by ASaiAnudeep** [comment]
I was able to use `form-data` with the following code:

```javascript
const options = {};
const form = new FormData();
form.append('my_file', fs.readFileSync(path), { contentType: 'application/xml', filename: 'jUnit.xml' });
options.data = form.getBuffer();
options.headers = form.getHeaders();
phin(options)
```
