### ISSUE TITLE
try parse JSON and catch error

### ISSUE THREAD

**Issue by jumoog** [ethanent/phin#48]
if JSON.parse fails it should return {}

maybe you can do someting like
```javascript
    try {
      return JSON.parse(data);
    }
    catch (error) {
      return {};
    }
```

**Comment by jumoog** [comment]
in my case the server returns not json if the server is overloaded

**Comment by ethanent** [comment]
I'm not so sure that {} is really reasonable. Maybe `null` would be more apt, but then still I think that most users would want to know if the parsing failed with a proper error rather than just by receiving `null`.
