### ISSUE TITLE
Deprecated usage of node _headers

### ISSUE THREAD

**Issue by JoaquinFernandez** [ethanent/phin#49]
**Describe the bug**

According to Node.js Deprecated APIs, OutgoingMessage.prototype._headers in v12 has been deprecated and on the other hand i see some deprecation logs while using Axios.

(node:89822) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**To Reproduce**
Calling an endpoint in Node.js v12

Environment:

Phin Version: 3.4.1
OS: OSX 10.15

**Related Links**

https://stackoverflow.com/questions/56697360/how-to-fix-node12388-dep0066-deprecationwarning-outgoingmessage-prototype
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames
http-party/http-server#537

**Comment by ethanent** [comment]
Odd. To my knowledge, _headers is not being accessed directly by Phin or Centra. I assume this is a mistake on the part of the implementation of the warning message.

**Comment by ethanent** [comment]
Closing unless others can confirm. I don’t think Phin or Centra access _headers, so perhaps this was an issue with another package.
