### ISSUE TITLE
Incorrect TypeScript "data" type declaration

### ISSUE THREAD

**Issue by ZitRos** [ethanent/phin#55]
Hello! My TypeScript complains on the very first example you provide in the [readme](https://www.npmjs.com/package/phin):

![image](https://user-images.githubusercontent.com/4989256/91291974-8c205680-e79e-11ea-947c-c09976e23e71.png)

I guess [this type declaration](https://github.com/ethanent/phin/blob/7d1b8ab94c205c7c1e33b7db1b1c992fb74faed9/types.d.ts#L21) has to be either `Object` (it has `toString` already) or `{ [key: string]: any, toString(): string }`.

What do you think? I will be happy to make a PR.

Thanks for great work.

**Comment by Sazzo** [comment]
Same here ^

**Comment by ethanent** [comment]
Thanks! A PR would be much appreciated if anyone is interested.

**Comment by jdforsythe** [comment]
Fixed in #65

**Comment by andreasonny83** [comment]
Please, release a new version with the fix
