### ISSUE TITLE
Types for "defaults" function

### ISSUE THREAD

**Issue by charles-allen** [ethanent/phin#57]
There is a disclaimer in the types file:

> // Default Options feature is not supported because it's basically impossible to write strongly-typed definitions for it.

I think perhaps [`Partial<T>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) is the piece of the puzzle you were missing? I tried to write a definition, but I'm not sure I understand the relation between JS source & TS types. Does this help? (might not be correct!)

```
export function defaults<T>(
  defaultOptions:
    | Partial<phin.IJSONResponseOptions>
    | Partial<IWithData<phin.IJSONResponseOptions>>
    | Partial<IWithForm<phin.IJSONResponseOptions>>
): (
  options:
    | phin.IJSONResponseOptions
    | IWithData<phin.IJSONResponseOptions>
    | IWithForm<phin.IJSONResponseOptions>
) => Promise<phin.IJSONResponse<T>>
```

**Comment by ethanent** [comment]
Thanks! This does seem like a good idea.

**Comment by jdforsythe** [comment]
I think this is now handled by optional properties in `IOptionsBase`

**Comment by sleeyax** [comment]
If anyone is wondering how exactly to extend the phin type definitions to include the suggested additions in your project, you can do so as follows:

1. Create the type declaration file, e.g. `types/phin.d.ts`:
```ts
import phin, { IWithData, IWithForm } from 'phin';

declare module 'phin' {
  export function defaults<T>(
    defaultOptions:
      | Partial<phin.IJSONResponseOptions>
      | Partial<IWithData<phin.IJSONResponseOptions>>
      | Partial<IWithForm<phin.IJSONResponseOptions>>
  ): (
    options:
      | phin.IJSONResponseOptions
      | IWithData<phin.IJSONResponseOptions>
      | IWithForm<phin.IJSONResponseOptions>
  ) => Promise<phin.IJSONResponse<T>>;
}
```
2. Update `tsconfig.json` as follows:
```json
"compilerOptions": {
    "typeRoots": [
      "./types/"
    ],
  }
```
3. This enables you to access `defaults` like this:
```ts
import p from 'phin';

export const httpClient = p.defaults({
  headers: {
    'User-Agent': 'My App',
  },
});
```
