### ISSUE TITLE
Cannot find name 'URL' - Broken type for IOptionsBase

### ISSUE THREAD

**Issue by frg-dev** [ethanent/phin#58]
I believe `URL` is not defined as a global unless you are using dom types. https://github.com/Microsoft/TypeScript/issues/10792

<img width="501" alt="Screen Shot 2020-11-05 at 7 17 44 PM" src="https://user-images.githubusercontent.com/68756803/98322149-9bd8ca00-1f9b-11eb-9440-84b03e51d37f.png">

As a workaround, adding a `d.ts` file with the following solves it for now.

```
declare type URL = import('url').URL;
```

**Comment by ethanent** [comment]
Thanks, a PR would be much appreciated if anyone is interested.
