### ISSUE TITLE
Setting local address?

### ISSUE THREAD

**Issue by jsieler** [ethanent/phin#9]
Is setting local address possible with this library?

**Comment by bdsomer** [comment]
@jsieler Could you please elaborate?

**Comment by jsieler** [comment]
@bdsomer as for example copied from "request" module:

> localAddress - local interface to bind for network connections.

Also, if your server do have multiple IP adresses, this option allows you to set interface address for desired connection.

**Comment by ethanent** [comment]
I'll be sure to implement this in a near release. 👍  Thanks for the suggestion!

**Comment by bdsomer** [comment]
@jsieler @ethanent This is an invalid issue. Already implemented as the `localAddress` property. See the documentation of the `options` paramater [here](https://nodejs.org/docs/latest/api/http.html#http_http_request_options_callback).

**Comment by ethanent** [comment]
@bdsomer We've been discussing phin, not the Node HTTP module...

**Comment by bdsomer** [comment]
@ethanent Yes it does! `Object.assign` causes all options passed in to be forwarded to the HTTP module. Go ahead, try it yourself!

**Comment by ethanent** [comment]
@bdsomer Oh, ha. Didn't realize we did that with the `opts` object. Thanks for reminding me!

@jsieler You should be good to go! Just add the `localAddress` property to the phin request options!
