### ISSUE TITLE
Package deprecated

### ISSUE THREAD

**Issue by ethanent** [ethanent/phin#91]
Please reply if you have any questions about Phin's deprecation.

Some popular alternatives (no endorsement, I may not have used them) include:

- Axios: [axios/axios](https://github.com/axios/axios)
- node-fetch: [node-fetch/node-fetch](https://github.com/node-fetch/node-fetch)
- The built-in HTTP library: https://nodejs.org/api/http.html

Please migrate to another HTTP request solution at your earliest convenience.

**Comment by yetzt** [comment]
But why?

**Comment by ASaiAnudeep** [comment]
@ethanent could you help us understanding the reason behind deprecating this package. Let me know if we can maintain phin and centra under our org - https://github.com/pactumjs

**Comment by yetzt** [comment]
[i made a fork](https://github.com/yetzt/node-phn), pulled in centra, fixed some bugs, added features, removed the tests for now because the testing library (`whew`) was unpublished too... it's pretty much a drop in replacement, i will use it in my own packages and implement updates and fixes as needed.

feel free to use it, send pull requests or give feedback.

**Comment by XuluWarrior** [comment]
@yetzt It would be good know what bugs were fixed and what features were added :)

**Comment by XuluWarrior** [comment]
Regarding the deprecation of this package, I note in the npm stats that it has 1 million weekly downloads.
It would be great if there was a (semi)official continuation of this project with a new maintainer
(@yetzt's efforts are already appreciated)

**Comment by yetzt** [comment]
> It would be good know what bugs were fixed and what features were added :)

#88 (compressed streams throw exception) and #79 (centra query is not exposed)

i'm looking into the other issues as well.

**Comment by ethanent** [comment]
Hi all, version 4.0.0 of the library has been released which uses Axios under the hood and is not deprecated currently. Give it a try! Thanks for your comments.

**Comment by sleeyax** [comment]
This situation is being handled poorly, OP. You're not answering any questions about the deprecation (like you said you would) and there are infinitely better options than just republishing axios... It's like no thought was put into this at all. 

I recommend to unpublish v4 and transform this issue into a discussion so we, as a community, can figure out the future of this package. Together. Communication is key in open source.

**Comment by ethanent** [comment]
Hi! Let's move the discussion about v4 to #92. Thank you.

**Comment by ethanent** [comment]
Maintainers wanted: #94
